<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DzServiceModule\Module'                                          => __DIR__ . '/Module.php',
  'DzServiceModule\Controller\Plugin\Factory\ServiceFactory'        => __DIR__ . '/src/DzServiceModule/Controller/Plugin/Factory/ServiceFactory.php',
  'DzServiceModule\Controller\Plugin\Service'                       => __DIR__ . '/src/DzServiceModule/Controller/Plugin/Service.php',
  'DzServiceModule\Exception\InvalidServiceException'               => __DIR__ . '/src/DzServiceModule/Exception/InvalidServiceException.php',
  'DzServiceModule\Factory\ServicesManagerFactory'                  => __DIR__ . '/src/DzServiceModule/Factory/ServicesManagerFactory.php',
  'DzServiceModule\Listener\AddServicesManagerListener'             => __DIR__ . '/src/DzServiceModule/Listener/AddServicesManagerListener.php',
  'DzServiceModule\Mapper\AbstractEntityMapper'                     => __DIR__ . '/src/DzServiceModule/Mapper/AbstractEntityMapper.php',
  'DzServiceModule\Mapper\DoctrineEntityMapper'                     => __DIR__ . '/src/DzServiceModule/Mapper/DoctrineEntityMapper.php',
  'DzServiceModule\Mapper\EntityMapperAwareInterface'               => __DIR__ . '/src/DzServiceModule/Mapper/EntityMapperAwareInterface.php',
  'DzServiceModule\Mapper\EntityMapperInterface'                    => __DIR__ . '/src/DzServiceModule/Mapper/EntityMapperInterface.php',
  'DzServiceModule\ModuleManager\Feature\ServicesProviderInterface' => __DIR__ . '/src/DzServiceModule/ModuleManager/Feature/ServicesProviderInterface.php',
  'DzServiceModule\Options\OptionsAwareInterface'                   => __DIR__ . '/src/DzServiceModule/Options/OptionsAwareInterface.php',
  'DzServiceModule\Service\DoctrineEntityService'                   => __DIR__ . '/src/DzServiceModule/Service/DoctrineEntityService.php',
  'DzServiceModule\Service\EntityService'                           => __DIR__ . '/src/DzServiceModule/Service/EntityService.php',
  'DzServiceModule\Service\EntityServiceInterface'                  => __DIR__ . '/src/DzServiceModule/Service/EntityServiceInterface.php',
  'DzServiceModule\Service\ServiceInterface'                        => __DIR__ . '/src/DzServiceModule/Service/ServiceInterface.php',
  'DzServiceModule\Service\ServicesPluginManager'                   => __DIR__ . '/src/DzServiceModule/Service/ServicesPluginManager.php',
  'DzServiceModule\Service\ServicesPluginManagerAwareInterface'     => __DIR__ . '/src/DzServiceModule/Service/ServicesPluginManagerAwareInterface.php',
);
